
events {}

http {
    upstream portal {
        server portal-cliente1:80;
    }

    upstream hotsite {
        server hotsite-cliente1:80;
    }

    upstream sign {
        server sign-cliente1:80;
    }

    server {
        listen 80;

        location /portal/ {
            proxy_pass http://portal/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /hotsite/ {
            proxy_pass http://hotsite/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /sign/ {
            proxy_pass http://sign/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
